# --- DATABASE ---
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/hospital_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

# --- SERVER ---
server.port=8080
server.ssl.enabled=false
app.frontend.url=${APP_FRONTEND_URL:http://localhost:3000}

# --- COOKIE SETTINGS (For HTTP) ---
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=Lax
server.servlet.session.cookie.path=/