spring.application.name=SmartHospitalSystem
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db
spring.datasource.username=root
spring.datasource.password=web01234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.connection.characterEncoding=utf8
spring.jpa.properties.hibernate.connection.CharSet=utf8mb4
# Enable HTTPS locally
server.port=8080
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=web01234
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat
app.frontend.url=http://localhost:3000

# --- SESSION COOKIE SECURITY ---

# 1. Allow the cookie to travel over HTTPS (Essential!)
server.servlet.session.cookie.secure=true

# 2. Allow the cookie to be sent between different ports (3000 -> 8080)
server.servlet.session.cookie.same-site=None

# 3. Ensure the cookie is valid for the whole domain
server.servlet.session.cookie.path=/

# 4. Give the cookie a standard name just in case
server.servlet.session.cookie.name=JSESSIONID